@echo off
echo Compiling FAQ...
cmd /C node src/compilers/faq.js"
echo Compiling Rules...
cmd /C "node src/compilers/rules.js"
echo Compiling Staff List...
cmd /C "node src/compilers/staffList.js"
echo Compiling Staff Tips ^& Tricks...
cmd /C "node src/compilers/staffTipsTricks.js"
echo compiling Useful Information...
cmd /C "node src/compilers/usefulInformation.js"
echo.
<nul set /p "=Everything compiled successfully. Press any key to exit."
pause >nul
