process.chdir(__dirname)
const cliProgress = require('cli-progress')
const { stripIndents } = require('common-tags')
const moment = require('moment')
const path = require('path')
const fs = require('fs')
const fileName = __filename.split(/(\\|\/)/g).pop().split('.')[0]
const data = require(path.join(process.cwd(), `./../data/${fileName}.json`)).faq
const lBar = new cliProgress.Bar({
  format: '  {bar} {percentage}% | Elapsed: {duration_formatted} | ETA: {eta_formatted} | {value}/{total}'
}, cliProgress.Presets.shades_classic); lBar.start(data.length + 3)

var text = ''
text += stripIndents`
  # :question: Frequently Asked Questions :question:
  It would be appreciated if you'd read this before asking any questions. :smile:

  *(If you haven't read #welcome yet, please do so.)*

  > Last Updated ${moment(new Date()).format('YYYY/MM/DD HH:mm:SS')}
`; lBar.increment()

data.forEach((d) => {
  text += `\n\n---\n### ${d.title}\n${d.description}`; lBar.increment()
})

text += `---\n\n\n#### Generated by \`src/compilers/${fileName}.js\`. 🚀\n`; lBar.increment()
fs.writeFile(path.join(process.cwd(), `./../built/${fileName}.md`), text, error => {
  if (error) {
    console.error(error)
    lBar.stop(); process.exit(1)
  } else {
    lBar.increment(); lBar.stop(); process.exit(0)
  }
})
