process.chdir(__dirname)
const cliProgress = require('cli-progress')
const { stripIndents } = require('common-tags')
const moment = require('moment-timezone')
const path = require('path')
const fs = require('fs')
const fileName = __filename.split(/(\\|\/)/g).pop().split('.')[0]
const data = require(path.join(process.cwd(), `./../data/${fileName}.json`)).categories
const lBar = new cliProgress.Bar({
  format: '  {bar} {percentage}% | Elapsed: {duration_formatted} | ETA: {eta_formatted} | {value}/{total}'
}, cliProgress.Presets.shades_classic); lBar.start(data.length + 3)

var text = ''
text += stripIndents`
  # :tools: __**Staff Tips & Tricks**__

  > Last Updated ${moment(new Date()).format('YYYY/MM/DD HH:mm:SS')}
`; text += '\n\n---\n'; lBar.increment()

data.forEach(c => {
  text += `\n# ${c.name}\n`
  if (c.subtitle) text += `*${c.subtitle}*\n`
  lBar.increment()
  lBar.setTotal(lBar.total + c.subCategories.length)
  c.subCategories.forEach(sc => {
    text += `\n## ${sc.name}\n`
    if (sc.subtitle) text += `*${sc.subtitle}*\n`
    lBar.increment()
    lBar.setTotal(lBar.total + sc.data.length)
    sc.data.forEach(d => {
      if (d.commandBeforeContent === true) {
        text += `- \`${d.command}\` - ${d.content}\n`
      } else {
        text += `- ${d.content} - \`${d.command}\`\n`
      }
      lBar.increment()
    })
  })
})

text += `\n---\n#### Generated by \`src/compilers/${fileName}.js\`. 🚀\n`; lBar.increment()
fs.writeFile(path.join(process.cwd(), `./../built/${fileName}.md`), text, error => {
  if (error) {
    console.error(error)
    lBar.stop(); process.exit(1)
  } else {
    lBar.increment(); lBar.stop(); process.exit(0)
  }
})
