process.chdir(__dirname)
const cliProgress = require('cli-progress')
const { stripIndents } = require('common-tags')
const moment = require('moment-timezone')
const path = require('path')
const fs = require('fs')
const fileName = __filename.split(/(\\|\/)/g).pop().split('.')[0]
const data = require(path.join(process.cwd(), `./../data/${fileName}.json`))
const lBar = new cliProgress.Bar({
  format: '  {bar} {percentage}% | Elapsed: {duration_formatted} | ETA: {eta_formatted} | {value}/{total}'
}, cliProgress.Presets.shades_classic); lBar.start(data.positions.length + 3)

var text = ''
text += stripIndents`
  # :tools: __**Official Staff Team**__

  > Last Updated ${moment(new Date()).format('YYYY/MM/DD HH:mm:SS')}
`; text += '\n\n---\n'; lBar.increment()

data.positions.forEach(p => {
  text += `- **${p.name}** - *${p.description}*\n`; lBar.increment()
  stf = data.staffMembers.filter(s => s.position === p.name)
  lBar.setTotal(lBar.total + stf.length)
  stf.forEach(s => {
    text += `  - **${s.username}#${s.discrim}** - \`${s.id}\`\n`
    if (s.bio) text += `    - ${s.bio}\n`
    if (s.timezone) {
      if (moment.tz.names().includes(s.timezone)) {
        text += `    - *(${s.timezone})*\n`
      } else {
        throw new Error(`'${s.timezone}' is not a valid timezone.`)
      }
    }
    lBar.increment()
  })
})

text += `\n---\n#### Generated by \`src/compilers/${fileName}.js\`. 🚀\n`; lBar.increment()
fs.writeFile(path.join(process.cwd(), `./../built/${fileName}.md`), text, error => {
  if (error) {
    console.error(error)
    lBar.stop(); process.exit(1)
  } else {
    lBar.increment(); lBar.stop(); process.exit(0)
  }
})
